from datetime import date,timedelta
from performance_engine import activity_load

def week_bounds(day=None):
 day=day or date.today();start=day-timedelta(days=day.weekday());return start,start+timedelta(days=6)

def week_summary(sessions,activities):
 planned=[s for s in sessions if s.get('status')!='cancelled'];done=[s for s in planned if s.get('status')=='completed' or s.get('completed_at')];pmin=sum(float(s.get('duration_min') or 0) for s in planned);amin=sum(float(s.get('actual_duration_min') or s.get('duration_min') or 0) for s in done);pdist=sum(float(s.get('distance_km') or 0) for s in planned);adist=sum(float(s.get('actual_distance_km') or 0) for s in done);activity_minutes=sum(float(a.get('duration_min') or 0) for a in activities)
 return {'planned_sessions':len(planned),'done_sessions':len(done),'session_pct':round(100*len(done)/len(planned)) if planned else 0,'planned_minutes':round(pmin),'done_minutes':round(amin),'minute_pct':round(100*amin/pmin) if pmin else 0,'planned_km':round(pdist,1),'done_km':round(adist,1),'activity_minutes':round(activity_minutes),'load':round(sum(activity_load(a) for a in activities))}

# Dates non confirmées = fenêtres stratégiques modifiables dans l'application.
def roadmap():
 return [
 {'name':'M1 · Semi Porto-Vecchio','start':'2026-09-16','end':'2026-10-18','focus':'Course / seuil / endurance','objective':'Semi Porto-Vecchio · 18/10/2026','weeks':['S1 Consolidation : 3 CAP dont seuil, 1 sortie longue 16–18 km, rugby/danse comptés en charge.','S2 Spécifique : 2×15 min allure semi, endurance, sortie 18–20 km progressive.','S3 Pic : dernière grosse sortie 18 km avec 2×4 km spécifique, volume réduit autour du rugby.','S4 Affûtage : -30 % volume, rappels allure, aucune musculation jambes lourde.','S5 Course : 2 footings courts + éducatifs, semi le dimanche, récupération ensuite.'], 'sessions':'CAP 3–4×/sem · natation récupération facultative · vélo facile 0–1× · force 1–2× selon gardes.'},
 {'name':'M2 · Transition trail / SaintéLyon','start':'2026-10-19','end':'2026-11-28','focus':'Trail / côtes / force / descente','objective':'SaintéLyon relais · 28/11/2026','weeks':['S1 récupération semi : marche, vélo souple, natation, 2 CAP très faciles.','S2 initiation trail : côtes courtes, footing vallonné, force chevilles/mollets/quadriceps.','S3 développement : côtes longues 6×3 min, sortie trail 1h30–1h45, technique descente.','S4 spécifique : sortie nocturne vallonnée, travail lampe/équipement, 1 séance tempo terrain.','S5 pic : sortie trail 2 h environ sans recherche de vitesse, puis baisse de charge.','S6 affûtage : 2 footings faciles + rappels côtes, SaintéLyon relais.'], 'sessions':'Trail/CAP 3× · force 2× puis 1× · natation 1× récupération · rugby intégré sans ajouter une séance dure le lendemain.'},
 {'name':'M3 · Reconstruction triathlon','start':'2026-11-29','end':'2027-01-03','focus':'Récupération / technique natation / force','objective':'Construire la base sans urgence chronométrique','weeks':['S1 récupération complète post-SaintéLyon.','S2 reprise : natation technique 2×, vélo Z2 1×, CAP facile 2×.','S3 base : natation 2×, vélo 2×, CAP 2×, force 2×.','S4 semaine allégée fêtes : fréquence conservée, volume réduit.','S5 reprise progressive et tests non maximaux si récupération correcte.'], 'sessions':'6–8 h/sem cible adaptable · priorité technique natation et régularité.'},
 {'name':'M4 · Base triathlon + Triathlon M','start':'2027-01-04','end':'2027-03-07','focus':'Aérobie / technique / force / premier enchaînement','objective':'Triathlon M de début de saison · fenêtre fin février/début mars','weeks':['S1–2 base : 2 natations, 2 vélos, 2 CAP, 2 renfo courts.','S3 charge : vélo long 2h30, CAP 1h20, CSS technique.','S4 récupération + test CSS/5 km selon fatigue.','S5–6 construction : tempo vélo, seuil CAP contrôlé, premier brick 1h45+15 min.','S7 spécifique M : natation 1500–2000 m, vélo 2 h avec tempo, brick 20–25 min.','S8 allégée : -25 % volume.','S9 Triathlon M utilisé comme répétition générale, sans taper majeur.'], 'sessions':'Natation 2× · vélo 2× · CAP 2–3× · force 1–2× · rugby/danse intégrés.'},
 {'name':'M5 · Marathon Aveiro','start':'2027-03-08','end':'2027-04-25','focus':'Endurance course / allure marathon / robustesse','objective':'Marathon Aveiro · fin avril 2027','weeks':['S1 transition du M puis sortie longue 1h40.','S2 20–22 km facile + bloc allure marathon court.','S3 24 km dont 2×4 km spécifique.','S4 récupération 18–20 km, vélo/natation entretien.','S5 26–28 km nutrition course.','S6 pic 28–30 km maximum selon tolérance, sans chercher le chrono à l’entraînement.','S7 taper -30 à -40 %, rappel allure.','S8 marathon : fréquence courte, sommeil/nutrition, course fin de semaine.'], 'sessions':'CAP 3–4× · natation 1–2× récupération · vélo 1× facile · force 1× entretien. Rugby à réduire si conflit avec longues sorties.'},
 {'name':'M6 · Reprise vélo + Mont Ventoux','start':'2027-04-26','end':'2027-05-23','focus':'Récupération marathon / vélo montagne','objective':'Ascension simple du Mont Ventoux · fenêtre mi-mai','weeks':['S1 récupération marathon : aucune intensité CAP.','S2 reprise vélo 2 h souple + natation 2× + CAP courte.','S3 côtes vélo : 2h30–3h, cadence et gestion d’effort.','S4 défi Mont Ventoux : remplace la sortie vélo longue ; lendemain récupération complète.'], 'sessions':'Vélo devient prioritaire · CAP minimale de maintien · natation 2×.'},
 {'name':'M7 · Half Annecy','start':'2027-05-24','end':'2027-06-27','focus':'Triathlon longue endurance / brick / eau libre','objective':'Half Ironman Annecy · juin 2027','weeks':['S1 récupération Ventoux + technique eau libre.','S2 vélo 3 h + brick 25 min, natation 2–2.5 km, CAP 1h20.','S3 spécifique : vélo 3h30 avec tempo + brick 35 min ; eau libre si possible.','S4 pic Half : simulation nutrition, vélo 3h30–4h, CAP longue 1h30.','S5 taper puis Half Annecy.'], 'sessions':'Natation 2–3× · vélo 2–3× · CAP 2–3× · brick 1× · force entretien.'},
 {'name':'M8 · Montagne / Cinglée du Ventoux','start':'2027-06-28','end':'2027-07-25','focus':'Endurance vélo / D+ / nutrition','objective':'Cinglée du Ventoux · fenêtre juillet 2027','weeks':['S1 récupération Half, volume très bas.','S2 vélo 3 h vallonné + force légère + natation récupération.','S3 vélo 4–5 h avec D+ progressif, alimentation 60–90 g glucides/h à tester selon tolérance.','S4 spécifique montagne : 5–6 h, gestion des ascensions répétées.','S5 Cinglée du Ventoux : défi = séance clé de la semaine, pas de longue sortie supplémentaire.'], 'sessions':'Vélo 3× · natation 2× · CAP 2× facile/brick · récupération renforcée.'},
 {'name':'M9 · Grand Colombier / endurance Full','start':'2027-07-26','end':'2027-08-15','focus':'Très longue endurance / D+ / fatigue contrôlée','objective':'Confrérie des Fêlés du Grand Colombier · fenêtre début août','weeks':['S1 récupération Cinglée + natation technique + CAP facile.','S2 long vélo 5 h + brick 40 min, natation longue 3 km.','S3 Fêlés du Grand Colombier : remplace le long vélo ; priorité nutrition, pacing et récupération.'], 'sessions':'Aucune accumulation artificielle de défis : 48–72 h faciles après très gros D+ selon récupération.'},
 {'name':'M10 · Spécifique LéMan Full','start':'2027-08-16','end':'2027-09-05','focus':'Spécifique Full / nutrition / bricks','objective':'Dernier bloc spécifique avant taper','weeks':['S1 5–6 h vélo Z2 + brick 45 min ; natation 3–3.5 km ; CAP 1h40 facile.','S2 simulation nutrition : vélo long 5 h avec portions allure cible + brick 60 min.','S3 dernière grosse semaine : volume élevé mais intensité basse, aucune recherche de record.'], 'sessions':'Natation 3× · vélo 3× · CAP 3× dont brick · force uniquement entretien.'},
 {'name':'M11 · Taper LéMan Full','start':'2027-09-06','end':'2027-09-30','focus':'Fraîcheur / spécificité / confiance','objective':'LéMan Full Distance · septembre 2027','weeks':['T-3 : -20 à -25 % volume, intensité spécifique conservée.','T-2 : -35 à -45 %, dernière sortie vélo moyenne + brick court.','Race week : séances courtes, eau libre technique, sommeil/nutrition/logistique ; aucun test maximal.','COURSE : 3,8 km natation · 180 km vélo · marathon, stratégie conservatrice et nutrition préparée.'], 'sessions':'Fréquence conservée, volume réduit progressivement ; priorité absolue à la fraîcheur.'}
 ]

def seed_roadmap(execute,query):
 # V7.2 roadmap is rendered from code; DB remains available for future editable blocks.
 return

def test_catalog():return {'running':['5 km','10 km','VMA','Seuil','FC seuil','Allure critique','Terrain personnalisé'],'cycling':['FTP','20 min','FC seuil','Puissance critique','Test côte'],'swimming':['CSS','200 m','400 m','1000 m','1500 m'],'strength':['Tractions','Dips','Squat','Gainage','Personnalisé']}
def suggested_tests(existing):
 types={(x.get('sport'),x.get('test_type')) for x in existing};out=[]
 if not any(s=='cycling' and t in ('FTP','20 min') for s,t in types):out.append('🚴 FTP vélo à établir')
 if not any(s=='swimming' and t=='CSS' for s,t in types):out.append('🏊 CSS natation à établir')
 if not any(s=='running' and t in ('5 km','Seuil','Allure critique') for s,t in types):out.append('🏃 Zones CAP à actualiser')
 return out
