def detailed_workout(sport, intensity, duration, objective=''):
    sport=(sport or '').lower(); intensity=(intensity or 'easy').lower(); duration=int(duration or 60)
    if sport=='running':
        if intensity in {'threshold','quality','hard'}:
            return {'summary':"15' facile + 3 x 8' soutenu / 3' trot + 10' facile",'warmup':"15 min très facile + mobilité + 3 accélérations progressives de 20 s.",'main':"3 x 8 min à effort contrôlé proche allure semi/seuil bas (RPE 7/10), récupération 3 min en trot très lent.",'cooldown':"10 min facile. Marche 3–5 min si besoin.",'intensity_target':"RPE 7/10 sur les blocs; rester régulier, jamais à bloc.",'nutrition':"Eau selon chaleur. Si >75 min, prévoir 30–45 g glucides/h.",'coach_note':objective or "Développer l'endurance à haute intensité sans créer une fatigue excessive."}
        if duration>=80:
            return {'summary':f"{duration} min endurance fondamentale",'warmup':"10–15 min très faciles.",'main':f"Courir en aisance respiratoire. Sur les 20 dernières minutes, accélérer légèrement uniquement si les sensations sont bonnes.",'cooldown':"5–10 min très faciles ou marche.",'intensity_target':"RPE 3–4/10, conversation possible.",'nutrition':"Boire régulièrement; au-delà de 90 min viser 30–60 g glucides/h.",'coach_note':objective or "Construire la tolérance à la durée."}
        return {'summary':f"{duration} min endurance facile",'warmup':"10 min très faciles.",'main':"Endurance fondamentale relâchée, sans chercher l'allure.",'cooldown':"5 min faciles.",'intensity_target':"RPE 3/10, conversation aisée.",'nutrition':"Hydratation selon conditions.",'coach_note':objective or "Accumuler du volume avec un faible coût de récupération."}
    if sport=='trail':
        return {'summary':f"{duration} min trail progressif",'warmup':"15 min faciles sur terrain simple.",'main':"Alterner course et marche active dans les montées. Descendre relâché, priorité à la technique et au contrôle.",'cooldown':"10 min faciles.",'intensity_target':"RPE moyen 4–5/10; montées courtes jusqu'à 7/10.",'nutrition':"Si >90 min: 40–60 g glucides/h + hydratation régulière.",'coach_note':objective or "Développer endurance musculaire, dénivelé et technique."}
    if sport=='cycling':
        hard=intensity in {'threshold','quality','hard'}
        return {'summary':f"{duration} min vélo {'spécifique' if hard else 'endurance'}",'warmup':"15 min souples, cadence progressive.",'main':("4 x 8 min soutenues / 4 min faciles, effort RPE 7/10." if hard else "Rouler majoritairement en endurance, cadence confortable. Ajouter 4 x 5 min de vélocité si les jambes sont bonnes."),'cooldown':"10 min très souples.",'intensity_target':("RPE 7/10 sur les blocs." if hard else "RPE 3–4/10."),'nutrition':"À partir de 90 min: 40–70 g glucides/h et 500–750 ml/h selon conditions.",'coach_note':objective or "Développer l'endurance cycliste."}
    if sport=='swimming':
        return {'summary':f"Natation {duration} min technique/endurance",'warmup':"300 m facile, nage variée.",'main':"8 x 50 m technique récup 15–20 s, puis 6 x 200 m régulier récup 20–30 s. Ajuster le nombre de répétitions à la durée disponible.",'cooldown':"200 m très facile.",'intensity_target':"Technique propre, RPE 4–6/10; ne pas dégrader le geste.",'nutrition':"Hydratation simple; glucides utiles surtout si séance longue ou enchaînée.",'coach_note':objective or "Améliorer économie de nage et continuité."}
    if sport=='strength':
        return {'summary':f"Renforcement {duration} min",'warmup':"8–10 min mobilité + activation tronc/hanches/épaules.",'main':"Tractions, pompes/dips, squat ou fente, charnière de hanche, mollets, gainage. 3–4 séries; garder 2 répétitions en réserve.",'cooldown':"Mobilité légère 5 min.",'intensity_target':"RPE 6–7/10, technique stricte, pas d'échec musculaire.",'nutrition':"Repas normal riche en protéines après la séance.",'coach_note':objective or "Robustesse générale et prévention."}
    return {'summary':f"Séance {duration} min",'warmup':"Échauffement progressif.",'main':objective or "Travail principal selon sensations.",'cooldown':"Retour au calme.",'intensity_target':"Effort contrôlé.",'nutrition':"Hydratation selon besoin.",'coach_note':objective or "Développement général."}
